name: Test and lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Upgrade npm
        run: npm i --location=global npm@latest
      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
      - name: Test 🔬
        run: npm test
        env:
          ROAR_CI_USER_EMAIL: ${{ secrets.ROAR_CI_USER_EMAIL }}
          ROAR_CI_USER_PASSWORD: ${{ secrets.ROAR_CI_USER_PASSWORD }}
          ROAR_FIREBASE_API_KEY: ${{ secrets.ROAR_FIREBASE_API_KEY }}
          ROAR_FIREBASE_APP_ID: ${{ secrets.ROAR_FIREBASE_APP_ID }}
          ROAR_FIREBASE_MEASUREMENT_ID: ${{ secrets.ROAR_FIREBASE_MEASUREMENT_ID }}
          ROAR_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.ROAR_FIREBASE_MESSAGING_SENDER_ID }}
          ROAR_FIREBASE_AUTH_DOMAIN: ${{ secrets.ROAR_FIREBASE_AUTH_DOMAIN }}
          ROAR_FIREBASE_PROJECT_ID: ${{ secrets.ROAR_FIREBASE_PROJECT_ID }}
          ROAR_FIREBASE_STORAGE_BUCKET: ${{ secrets.ROAR_FIREBASE_STORAGE_BUCKET }}
      - name: Lint
        run: npm run lint

      - name: Check format
        run: npm run format:check
